"""add user ai preferences

Revision ID: 00109cb75959
Revises: dc5a997a2635
Create Date: 2025-05-09 02:22:45.646331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00109cb75959'
down_revision = 'dc5a997a2635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_bg_color_r', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_bg_color_g', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_bg_color_b', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_font_color_r', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_font_color_g', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_font_color_b', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retry_prompt_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enable_markdown_prompt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('markdown_prompt_template', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('markdown_prompt_template')
        batch_op.drop_column('enable_markdown_prompt')
        batch_op.drop_column('retry_prompt_template')
        batch_op.drop_column('ai_font_color_b')
        batch_op.drop_column('ai_font_color_g')
        batch_op.drop_column('ai_font_color_r')
        batch_op.drop_column('ai_bg_color_b')
        batch_op.drop_column('ai_bg_color_g')
        batch_op.drop_column('ai_bg_color_r')

    # ### end Alembic commands ###
