"""Add active_ai_service_id to User model

Revision ID: 04acd4837934
Revises: 108de8302fa3
Create Date: 2025-05-03 06:50:32.536731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04acd4837934'
down_revision = '108de8302fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_ai_service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(op.f('fk_user_active_ai_service_id_ai_service'), 'ai_service', ['active_ai_service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_user_active_ai_service_id_ai_service'), type_='foreignkey')
        batch_op.drop_column('active_ai_service_id')

    # ### end Alembic commands ###
