"""Add user ownership to PromptTemplate

Revision ID: 108de8302fa3
Revises: a30e8b9cd57f
Create Date: 2025-05-03 00:42:06.714327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108de8302fa3'
down_revision = 'a30e8b9cd57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_prompttemplate_user_id_name', ['user_id', 'name'], unique=False)
        batch_op.create_unique_constraint('uq_user_template_name', ['user_id', 'name'])
        batch_op.create_foreign_key('fk_prompt_template_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_prompt_template_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('uq_user_template_name', type_='unique')
        batch_op.drop_index('ix_prompttemplate_user_id_name')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
