"""Add enable_streaming to AIService

Revision ID: 23b441e3fcda
Revises: 90aa182f3787
Create Date: 2025-05-04 01:22:56.636732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b441e3fcda'
down_revision = '90aa182f3787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_streaming', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_service', schema=None) as batch_op:
        batch_op.drop_column('enable_streaming')

    # ### end Alembic commands ###
