"""Add SubscriptionConfig model and association table

Revision ID: 50a979842e8f
Revises: ced2f051a81d
Create Date: 2025-05-07 17:41:02.848644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a979842e8f'
down_revision = 'ced2f051a81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('distribution_frequency', sa.String(length=20), nullable=False),
    sa.Column('distribution_day', sa.Integer(), nullable=True),
    sa.Column('distribution_time', sa.Time(), nullable=False),
    sa.Column('points_to_distribute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_config_group_association',
    sa.Column('subscription_config_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['subscription_config_id'], ['subscription_config.id'], ),
    sa.PrimaryKeyConstraint('subscription_config_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_config_group_association')
    op.drop_table('subscription_config')
    # ### end Alembic commands ###
