"""Add is_default field to AIService model

Revision ID: 90aa182f3787
Revises: 04acd4837934
Create Date: 2025-05-03 08:54:24.858680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90aa182f3787'
down_revision = '04acd4837934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_service', schema=None) as batch_op:
        # Add server_default='0' for SQLite compatibility with NOT NULL boolean
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_service', schema=None) as batch_op:
        batch_op.drop_column('is_default')
    # Downgrade doesn't need server_default, it just drops the column.
    # ### end Alembic commands ###
