"""Add auto_save_on_navigate to User model

Revision ID: 9bba3c6e4dc5
Revises: f12732d5b1d2
Create Date: 2025-05-02 20:08:15.896781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bba3c6e4dc5'
down_revision = 'f12732d5b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_save_on_navigate', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_save_on_navigate')

    # ### end Alembic commands ###
