"""Update InvitationCode model with max_uses and times_used

Revision ID: ced2f051a81d
Revises: fa8c66c839d0
Create Date: 2025-05-07 17:18:00.849453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced2f051a81d'
down_revision = 'fa8c66c839d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_uses', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('times_used', sa.Integer(), nullable=False))
        batch_op.drop_column('is_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_used', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('times_used')
        batch_op.drop_column('max_uses')

    # ### end Alembic commands ###
