"""Add ApiCallLog table again

Revision ID: dc5a997a2635
Revises: 981b13842fad
Create Date: 2025-05-08 16:54:45.391844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5a997a2635'
down_revision = '981b13842fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ai_service_id', sa.Integer(), nullable=True),
    sa.Column('ai_service_name', sa.String(length=150), nullable=False),
    sa.Column('is_system_service', sa.Boolean(), nullable=False),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('points_deducted', sa.Integer(), nullable=False),
    sa.Column('prompt_length', sa.Integer(), nullable=True),
    sa.Column('response_length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ai_service_id'], ['ai_service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
