"""Add setting_book_id to FileSystemItem

Revision ID: f12732d5b1d2
Revises: 
Create Date: 2025-05-02 05:08:31.518481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12732d5b1d2'
down_revision = None
branch_labels = None
depends_on = None

# 定义一个约束名称
CONSTRAINT_NAME = 'fk_filesystem_items_setting_book_id'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filesystem_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_book_id', sa.Integer(), nullable=True))
        # 为外键约束提供名称
        batch_op.create_foreign_key(CONSTRAINT_NAME, 'filesystem_items', ['setting_book_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filesystem_items', schema=None) as batch_op:
        # 移除约束时也要使用相同的名称
        batch_op.drop_constraint(CONSTRAINT_NAME, type_='foreignkey')
        batch_op.drop_column('setting_book_id')

    # ### end Alembic commands ###
