"""Initial database schema with all models

Revision ID: fa8c66c839d0
Revises: 2300dd94416c
Create Date: 2025-05-07 16:43:25.032523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8c66c839d0'
down_revision = '2300dd94416c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_change_required', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_change_required')

    # ### end Alembic commands ###
